// Categories Data
export const productCategories = [
    { name: "Mac", icon: "/images/Accessories/Icons/icon-product-mac.png" },
    { name: "iPad", icon: "/images/Accessories/Icons/icon-product-ipad.png" },
    { name: "iPhone", icon: "/images/Accessories/Icons/icon-product-iphone.png" },
    { name: "Watch", icon: "/images/Accessories/Icons/icon-product-watch.png" },
    { name: "Apple Vision Pro", icon: "/images/Accessories/Icons/icon-product-vision-pro.png" },
    { name: "TV & Home", icon: "/images/Accessories/Icons/icon-product-tv.png" },
    { name: "Beats by Dr. Dre", icon: "/images/Accessories/Icons/icon-product-beats.png" },
]

export const categoryCategories = [
    { name: "New Arrivals", icon: "/images/Accessories/Icons/icon-category-new-arrivals.png" },
    { name: "Cases & Protection", icon: "/images/Accessories/Icons/icon-category-cases-protection.png" },
    { name: "Charging Essentials", icon: "/images/Accessories/Icons/icon-category-charging-essentials.png" },
    { name: "MagSafe", icon: "/images/Accessories/Icons/icon-category-magsafe.png" },
    { name: "Headphones & Speakers", icon: "/images/Accessories/Icons/icon-category-audio-music.png" },
    { name: "Apple Watch Bands", icon: "/images/Accessories/Icons/icon-category-watch-bands.png" },
    { name: "Apple Vision Pro", icon: "/images/Accessories/Icons/icon-product-vision-pro.png" },
    { name: "Home Office", icon: "/images/Accessories/Icons/icon-category-house-wifi.png" },
    { name: "Mice & Keyboards", icon: "/images/Accessories/Icons/icon-category-mice-keyboards.png" },
    { name: "AirTag and Accessories", icon: "/images/Accessories/Icons/icon-category-airtag.png" },
    { name: "Health & Fitness", icon: "/images/Accessories/Icons/icon-category-health-fitness.png" },
    { name: "Gaming", icon: "/images/Accessories/Icons/icon-category-gaming.png" },
    { name: "Photography", icon: "/images/Accessories/Icons/icon-category-photography-creativity.png" },
    { name: "Creative Tools", icon: "/images/Accessories/Icons/icon-category-creative-tools.png" },
    { name: "Smart Home Accessories", icon: "/images/Accessories/Icons/icon-category-home-automation.png" },
    { name: "Software", icon: "/images/Accessories/Icons/icon-category-software.png" },
    { name: "Storage", icon: "/images/Accessories/Icons/icon-category-storage.png" },
]

// Products Data
export const iPhoneAccessories = [
    {
        id: 1,
        name: "iPhone 16 Plus Silicone Case with MagSafe – Peony",
        price: "$49.00",
        image: "/images/Accessories/Image_product/MDGR4.png",
        rating: 4,
        colors: ["#4A90E2", "#FF69B4", "#FF6B6B", "#FFA500", "#FFD700", "#32CD32"],
        isNew: true,
    },
    {
        id: 2,
        name: "iPhone 16 Pro Clear Case with MagSafe",
        price: "$49.00",
        image: "/images/Accessories/Image_product/iphone_case_gold.png",
        rating: 4,
        colors: [],
    },
    {
        id: 3,
        name: "iPhone 16e Silicone Case – Winter Blue",
        price: "$39.00",
        image: "/images/Accessories/Image_product/iphone_case_blue.png",
        rating: 4,
        colors: ["#4682B4", "#FF69B4", "#4A90E2", "#2F4F4F"],
    },
    {
        id: 4,
        name: "20W USB-C Power Adapter",
        price: "$19.00",
        image: "/images/Accessories/Image_product/usbC_20w.png",
        rating: 5,
        colors: [],
    },
    {
        id: 5,
        name: "MagSafe Charger (1m)",
        price: "$55.00",
        image: "/images/Accessories/Image_product/magsafe.png",
        rating: 4,
        colors: [],
    },
    {
        id: 6,
        name: "30W USB-C Power Adapter",
        price: "$39.00",
        image: "/images/Accessories/Image_product/usbC_30w.png",
        rating: 4,
        colors: [],
    },
    {
        id: 7,
        name: "240W USB-C Charge Cable (2 m)",
        price: "$29.00",
        image: "/images/Accessories/Image_product/usb_c_240w.png",
        rating: 4,
        colors: [],
    },
    {
        id: 8,
        name: "iPhone FineWoven Wallet with MagSafe - Deep Blue",
        price: "$39.00",
        image: "/images/Accessories/Image_product/wallet_deepblue.png",
        rating: 4,
        colors: [],
    },
    {
        id: 9,
        name: "Beats USB-C to USB-C Woven Cable (1.5 m / 5 ft) - Rapid Red",
        price: "$19.00",
        image: "/images/Accessories/Image_product/c_to_c_red.png",
        rating: 4,
        colors: [],
    },
    {
        id: 10,
        name: "OtterBox Lumen Series Case with MagSafe for iPhone 16 Pro-Blue",
        price: "$49.00",
        image: "/images/Accessories/Image_product/iphone_case_problue.png",
        colors: [],
    },
    
]

export const iPadAccessories = [
    {
        id: 1,
        name: "Apple Pencil (USB-C)",
        price: "$79.00",
        image: "/images/Accessories/Image_product/apple_pen.png",
        rating: 5,
    },
    {
        id: 2,
        name: "Magic Keyboard Folio for iPad (A16)",
        price: "$249.00",
        image: "/images/Accessories/Image_product/keyboard_a16.png",
        rating: 4,
    },
    {
        id: 3,
        name: "Smart Folio for iPad (A16) - Sky Blue",
        price: "$79.00",
        image: "/images/Accessories/Image_product/ipad_sky.png",
        rating: 4,
    },
    {
        id: 4,
        name: "Apple Pencil Pro",
        price: "$129.00",
        image: "/images/Accessories/Image_product/apple_penpro.png",
        rating: 5,
    },
    {
        id: 5,
        name: "Magic Keyboard for iPad Pro Air 11-inch (M3)",
        price: "$249.00",
        image: "/images/Accessories/Image_product/keyboard_m3.png",
        rating: 5,
    },
    {
        id: 6,
        name: "Smart Folio for iPad Pro Air 11-inch (M3) - Sage",
        price: "$79.00",
        image: "/images/Accessories/Image_product/ipad_sage.png",
        rating: 5,
    },
    {
        id: 7,
        name: "Magic Keyboard for iPad Pro 13-inch (M4) - White",
        price: "$349.00",
        image: "/images/Accessories/Image_product/keyboard_m4.png",
        rating: 5,
    },
    {
        id: 8,
        name: "Magic Keyboard for iPad Pro 13-inch (M4) - Denim",
        price: "$99.00",
        image: "/images/Accessories/Image_product/ipad_denim.png",
        rating: 5,
    },
    {
        id: 9,
        name: "Smart Folio for iPad mini (A17 Pro) - Light Violet",
        price: "$59.00",
        image: "/images/Accessories/Image_product/ipad_lightviolet.png",
        rating: 5,
    },
]

export const watchBands = [
    {
        id: 1,
        name: "46mm Pride Edition Sport Band - M/L",
        price: "$49.00",
        image: "/images/Accessories/Image_product/band_lgbt.png",
        rating: 5,
    },
    {
        id: 2,
        name: "46mm Periwinkle Sport Loop",
        price: "$49.00",
        image: "/images/Accessories/Image_product/band_blue.png",
        rating: 4,
    },
    {
        id: 3,
        name: "46mm Tangerine Sport Band - M/L",
        price: "$49.00",
        image: "/images/Accessories/Image_product/band_orange.png",
        rating: 4,
    },
    {
        id: 4,
        name: "46mm Gold Link Bracelet",
        price: "$349.00",
        image: "/images/Accessories/Image_product/band_gold.png",
        rating: 4,
    },
    {
        id: 5,
        name: "49mm Black Titannium Milanese Loop - Medium",
        price: "$199.00",
        image: "/images/Accessories/Image_product/band_medium.png",
        rating: 4,
    },
    {
        id: 6,
        name: "46mm Green/Grey Nike Sport Loop",
        price: "$49.00",
        image: "/images/Accessories/Image_product/band_nike.png",
        rating: 4,
    },
    {
        id: 7,
        name: "46mm Peony Braided Solo Loop - Size 6",
        price: "$99.00",
        image: "/images/Accessories/Image_product/band_pink.png",
        rating: 4,
    },
    {
        id: 8,
        name: "46mm Natural Milanese Loop - M/L",
        price: "$99.00",
        image: "/images/Accessories/Image_product/band_natural.png",
        rating: 4,
    },
    {
        id: 9,
        name: "Apple Watch Hermès - 42mm Beige de Weimar/Blanc Bridon Attelage Double Tour",
        price: "$449.00",
        image: "/images/Accessories/Image_product/band_hermes.png",
        rating: 4,
    },
    {
        id: 10,
        name: "Apple Watch Hermès - 49mm Bleu Hydra En Mer",
        price: "$449.00",
        image: "/images/Accessories/Image_product/band_hermes_blue.png",
        rating: 4,
    },

]

export const macAccessories = [
    {
        id: 1,
        name: "Studio Display",
        price: "$1,599.00",
        image: "/images/Accessories/Image_product/studio_display.png",
        rating: 4,
    },
    {
        id: 2,
        name: "Magic Keyboard with Touch ID and Numeric Keypad",
        price: "$199.00",
        image: "/images/Accessories/Image_product/numberic_keyboard.png",
        rating: 4,
    },
    {
        id: 3,
        name: "Magic Mouse",
        price: "$99.00",
        image: "/images/Accessories/Image_product/magic_mouse.png",
        rating: 4,
    },
    {
        id: 4,
        name: "Magic Trackpad",
        price: "$149.00",
        image: "/images/Accessories/Image_product/magic_trackpad.png",
        rating: 4,
    },
    {
        id: 5,
        name: "USB-C to MagSafe 3 Cable (2 m) - Sky Blue",
        price: "$49.00",
        image: "/images/Accessories/Image_product/cap_skyblue.png",
        rating: 4,
    },
    {
        id: 6,
        name: "USB-C Digital AV Multiport Adapter",
        price: "$199.00",
        image: "/images/Accessories/Image_product/usbC_av.png",
        rating: 4,
    },
    {
        id: 7,
        name: "240W USB-C Charge Cable (2 m)",
        price: "$29.00",
        image: "/images/Accessories/Image_product/usb_c_240w.png",
        rating: 4,
    },
    {
        id: 8,
        name: "Thunderbolt 5 (USB-C) Pro Cable (1 m)",
        price: "$199.00",
        image: "/images/Accessories/Image_product/capden.png",
        rating: 4,
    },
    {
        id: 9,
        name: "70W USB-C Power Adapter",
        price: "$199.00",
        image: "/images/Accessories/Image_product/usbc_70w.png",
        rating: 4,
    },
    {
        id: 10,
        name: "Polishing Cloth ",
        price: "$19.00",
        image: "/images/Accessories/Image_product/polishing_clouth.png",
        rating: 4,
    },

]

export const soundEssentials = [
    {
        id: 1,
        name: "AirPods Pro 2",
        price: "$249.00",
        image: "/images/Accessories/Image_product/airpod_pro2.png",
        rating: 5,
    },
    {
        id: 2,
        name: "AirPods 4 with Active Noise Cancellation",
        price: "$179.00",
        image: "/images/Accessories/Image_product/airpod4.png",
        rating: 4,
    },
    {
        id: 3,
        name: "AirPods Max - Midnight",
        price: "$549.00",
        image: "/images/Accessories/Image_product/airpodmax.png",
        rating: 4,
    },
    {
        id: 4,
        name: "HomePod Mini - Midnight",
        price: "$149.00",
        image: "/images/Accessories/Image_product/homepod_midnight.png",
        rating: 4,
    },
    {
        id: 5,
        name: "HomePod Mini - Blue",
        price: "$149.00",
        image: "/images/Accessories/Image_product/homepod_blue.png",
        rating: 4,
    },
    {
        id: 6,
        name: "Beats Studio Pro Wireless Headphones - Sandstone",
        price: "$349.99",
        image: "/images/Accessories/Image_product/headphone_sandstore.png",
        rating: 4,
    },
    {
        id: 7,
        name: "Beats Studio Buds + True Wireless Noise Cancelling Earbuds - Transparent",
        price: "$169.99",
        image: "/images/Accessories/Image_product/airpod_transparent.png",
        rating: 4,
    },
    {
        id: 8,
        name: "Beats Fit Pro True Wireless Earphones - Stone Purple",
        price: "$199.00",
        image: "/images/Accessories/Image_product/airpod_purple.png",
        rating: 4,
    },
    {
        id: 9,
        name: "Beats Flex - All-Day Wireless Earphones - Flame Blue",
        price: "$69.99",
        image: "/images/Accessories/Image_product/flame_blue.png",
        rating: 4,
    },
]

export const airTagProducts = [
    {
        id: 1,
        name: "AirTag",
        price: "$29.00",
        image: "/images/Accessories/Image_product/airtag.png",
        rating: 5,
    },
    {
        id: 2,
        name: "AirTag 4 pack",
        price: "$99.00",
        image: "/images/Accessories/Image_product/airtag4.png",
        rating: 5,
    },
    {
        id: 3,
        name: "AirTag FineWoven Key Ring - Blackberry",
        price: "$35.00",
        image: "/images/Accessories/Image_product/airtag_blackberry.png",
        rating: 4,
    },
    {
        id: 4,
        name: "Belkin Secure Holder with Strap for AirTag - White",
        price: "$12.95",
        image: "/images/Accessories/Image_product/airtag_white.png",
        rating: 4,
    },
    {
        id: 5,
        name: "Belkin Secure Holder with Strap for AirTag (4 - pack)",
        price: "$39.00",
        image: "/images/Accessories/Image_product/airtag_4.png",
        rating: 4,
    },
    {
      id: 6,
      name: "Belkin Secure Holder with Wire Cable for AirTag",
      price: "$19.00",
      image: "/images/Accessories/Image_product/airtag_wire.png",
      rating: 4,
  },
  {
    id: 7,
    name: "Belkin Secure Holder with Carabiner for AirTag",
    price: "$19.95",
    image: "/images/Accessories/Image_product/airtag_carabiner.png",
    rating: 4,
},
]
  